# Generated by Django 4.2.1 on 2023-05-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_resource_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='info',
            new_name='name',
        ),
    ]
