# Generated by Django 4.2.1 on 2023-05-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_info_resource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='about',
            field=models.TextField(default=0, max_length=300),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
