# Generated by Django 4.2.1 on 2023-05-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ongoingevent_pastevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donate',
            new_name='donor',
        ),
    ]
