# Generated by Django 4.2.1 on 2023-05-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_donate_donor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='testimony',
        ),
        migrations.AddField(
            model_name='program',
            name='details',
            field=models.TextField(default=0, max_length=300),
        ),
    ]
