# Generated by Django 4.2.1 on 2023-05-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_program_facilitator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('Location', models.CharField()),
                ('time', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
